#! /usr/bin/env python3
import sys, os, argparse, subprocess, json, datetime, pprint, traceback
from pathlib import Path

# ======================================================================

def main(args: argparse.Namespace):
    args.output_dir.mkdir(exist_ok=True)
    nextclade_dir = clone(output_dir=args.output_dir)
    recent_dirs = find_recent_versions(nextclade_dir)
    result = {
        "  version": "clades-v2",
        "  date": datetime.date.today().strftime("%Y-%m-%d"),
        "  creator": sys.argv[0],
        }
    for subtype, sdir in recent_dirs.items():
        result[subtype] = extract_clades(subtype=subtype, source_dir=sdir)
    generate_clades_v2(result)

# ----------------------------------------------------------------------

def extract_clades(subtype: str, source_dir: Path) -> list:
    ha1_offset, ha2_offset = get_ha_offset(source_dir) # 0-based in nuc pos
    # print(subtype, ha2_offset)
    return get_clade_data(source_dir, ha1_offset=ha1_offset, ha2_offset=ha2_offset)

# ----------------------------------------------------------------------

def get_clade_data(source_dir: Path, ha1_offset: int, ha2_offset: int) -> list:

    ha2_offset_aa = (ha2_offset - ha1_offset) // 3
    def convert_mutations(mutations: dict):
        res = {}
        if mutations.get("HA1") or mutations.get("HA2"):
            res["aa"] = [ha1_mut[1:] for ha1_mut in mutations.get("HA1", [])] + [f"{int(ha2_mut[1:-1]) + ha2_offset_aa}{ha2_mut[-1]}" for ha2_mut in mutations.get("HA2", [])]
        if mutations.get("nuc"):                   # h1, nuc only for 6B.1A
            res["nuc"] = [f"{int(nuc_mut[1:-1]) - ha1_offset}{nuc_mut[-1]}" for nuc_mut in mutations.get("nuc", [])]
        return res

    clades = []
    def collect_clades(root):
        clade = root.get("branch_attrs", {}).get("labels", {}).get("clade")
        if clade:
            mutations = root["branch_attrs"]["mutations"]
            # print(clade, mutations)
            clades.append({"N": clade, **convert_mutations(mutations)})
        for child in root.get("children", []):
            collect_clades(child)

    data = json.load(source_dir.joinpath("tree.json").open())
    collect_clades(data["tree"])
    return clades

# ----------------------------------------------------------------------

def get_ha_offset(source_dir: Path) -> int:
    # 0-based in nuc positions
    # https://m.ensembl.org/info/website/upload/gff3.html
    ha1_offset = 0
    ha2_offset = 0
    for line in source_dir.joinpath("genemap.gff").open():
        if line[0] != "#":
            seqid, source, type_, start, end, score, strand, phase, attributes = line.strip().split("\t")
            if "HA1" in attributes:
                ha1_offset = int(start) - 1
            elif "HA2" in attributes:
                ha2_offset = int(start) - 1
    return ha1_offset, ha2_offset

# ----------------------------------------------------------------------

sIgnoreDirs = [".git", ".github", "infra", "scripts", "sars-cov-2"]
sSubtype = {"flu_yam_ha": "B/Yam", "flu_vic_ha": "B/Vic", "flu_h1n1pdm_ha": "A(H1N1)", "flu_h3n2_ha": "A(H3N2)"}

def find_recent_versions(nextclade_dir: Path):
    all_dirs = []
    for root, dirs, files in os.walk(nextclade_dir):
        if "tree.json" in files:
            all_dirs.append(Path(root))
        else:
            for idir in sIgnoreDirs:
                if idir in dirs:
                    dirs.remove(idir)
    all_dirs.sort(key=lambda dd: dd.parent.name, reverse=True)
    recent_dirs = {}
    for adir in all_dirs:
        subtype = sSubtype[adir.parents[4].name]
        if not subtype in recent_dirs:
            recent_dirs[subtype] = adir
    return recent_dirs

# ----------------------------------------------------------------------

def generate_clades_v2(data: dict, indent: int = 4):
    # print(json.dumps(data, indent=indent))
    key_order = ["  version", "  date", "  creator", "A(H1N1)", "A(H3N2)", "B/Vic", "B/Yam"]
    print("{")
    for key in key_order:
        val = data.get(key)
        if isinstance(val, str):
            print(f"{' ':{indent}}\"{key}\": \"{val}\",")
        else:
            print(f"{' ':{indent}}\"{key}\": [")
            for en in val[:-1]:
                print(f"{' ':{indent * 2}}{json.dumps(en)},")
            print(f"{' ':{indent * 2}}{json.dumps(val[-1])}\n{' ':{indent}}],")
    for k, v in data.items():
        if k not in key_order:
            print(f"{' ':{indent}}\"{key}\": {json.dumps(val)},")

    print(f"{' ':{indent}}\" \": \"\"")
    print("}")

# ----------------------------------------------------------------------

def clone(output_dir: Path) -> Path:
    nextclade_dir = output_dir.joinpath("nextclade_data")
    if nextclade_dir.exists():
        subprocess.check_call(["git", "-C", str(nextclade_dir), "pull", "-q"])
    else:
        subprocess.check_call(["git", "-C", str(output_dir), "clone", "https://github.com/nextstrain/nextclade_data/"])
    return nextclade_dir

# ======================================================================


try:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output_dir", type=Path)
    args = parser.parse_args()
    exit_code = main(args) or 0
except Exception as err:
    print(f"> {err}\n{traceback.format_exc()}", file=sys.stderr)
    exit_code = 1
exit(exit_code)

# ======================================================================
