#! /bin/bash
set -o errexit -o errtrace -o pipefail -o nounset # -o xtrace
if [[ $# -ne 1 ]]; then
    echo "> $0 bvic" >&2
    echo "> $0 byam" >&2
    echo "> $0 h1" >&2
    echo "> $0 h3" >&2
    exit 1
fi
SUBTYPE="$1"
TAL="$(dirname $0)/${SUBTYPE}.tal"
declare -A CUMUL=([bvic]=10 [h1]=0.1 [h3]=10)
LAST_DATE=2021

# ----------------------------------------------------------------------------------------------------

if [[ ! -f ${SUBTYPE}/${SUBTYPE}.tjz ]]; then
    ${AE_ROOT}/bin/tree-to-json --populate ${SUBTYPE} --ladderize --print-cumulative 20 --remove-if-cumulative-more-than ${CUMUL[${SUBTYPE}]} $(cat ${SUBTYPE}/garli-best.txt) ${SUBTYPE}/${SUBTYPE}.tjz
fi
if [[ ! -f ${SUBTYPE}/${SUBTYPE}.pdf ]]; then
    tal -s ${TAL} ${SUBTYPE}/${SUBTYPE}.tjz ${SUBTYPE}/${SUBTYPE}.txt ${SUBTYPE}/${SUBTYPE}.pdf
fi

# ----------------------------------------------------------------------------------------------------

if [[ ! -f ${SUBTYPE}/${SUBTYPE}.asr.tjz ]]; then
    ASR_STATES=$(cat ${SUBTYPE}/raxml-asr-best.txt | sed 's/ancestralTree/ancestralStates/')
    ${AE_ROOT}/bin/tree-to-json --populate ${SUBTYPE} --asr-tree $(cat ${SUBTYPE}/raxml-asr-best.txt) --asr-states ${ASR_STATES} --ladderize --print-cumulative 20 --remove-if-cumulative-more-than ${CUMUL[${SUBTYPE}]} $(cat ${SUBTYPE}/garli-best.txt) ${SUBTYPE}/${SUBTYPE}.asr.tjz
fi
if [[ ! -f ${SUBTYPE}/${SUBTYPE}.asr.pdf ]]; then
    tal -s ${TAL} -D aa-transitions-method=imported ${SUBTYPE}/${SUBTYPE}.asr.tjz ${SUBTYPE}/${SUBTYPE}.asr.txt ${SUBTYPE}/${SUBTYPE}.asr.pdf
fi

# ----------------------------------------------------------------------------------------------------

if [[ ! -f ${SUBTYPE}/${SUBTYPE}.after-${LAST_DATE}.tjz ]]; then
    ${AE_ROOT}/bin/tree-to-json --populate ${SUBTYPE} --ladderize --remove-leaves-isolated-before ${LAST_DATE} --remove-if-cumulative-more-than ${CUMUL[${SUBTYPE}]} $(cat ${SUBTYPE}/garli-best.txt) ${SUBTYPE}/${SUBTYPE}.after-${LAST_DATE}.tjz
fi
if [[ ! -f ${SUBTYPE}/${SUBTYPE}.after-${LAST_DATE}.pdf ]]; then
    tal -s ${TAL} ${SUBTYPE}/${SUBTYPE}.after-${LAST_DATE}.tjz ${SUBTYPE}/${SUBTYPE}.after-${LAST_DATE}.txt ${SUBTYPE}/${SUBTYPE}.after-${LAST_DATE}.pdf
fi

# ----------------------------------------------------------------------------------------------------
