#! /usr/bin/env bash
set -o errexit -o errtrace -o pipefail -o nounset # -o xtrace

submit_tree()
{
    NODE="$1"
    SUBTYPE="$2"
    ( ${AE_ROOT}/proj/weekly-tree/raxml --node ${NODE} ${SUBTYPE} && ${AE_ROOT}/proj/weekly-tree/garli --node ${NODE} ${SUBTYPE} && ${AE_ROOT}/proj/weekly-tree/pdf ${SUBTYPE} ) >${SUBTYPE}/submit.log 2>&1 &
}

submit_tree i22 h3
submit_tree i20 h1
submit_tree i21 bvic
